### ISSUE TITLE
Säljer 1 produkt får betalt för alla som den frågar efter

### ISSUE THREAD

**Issue by NEAC2004** [ThunbergOlle/virtcon#23]
t.ex om någon frågar efter att köpa 400 guld för 200 per styck och jag säljer 1 guld för 200 så får jag betalt som om jag hade sålt 400 för 200 per styck

**Comment by ThunbergOlle** [comment]
Ska kolla på detta ASAP.

**Comment by ThunbergOlle** [comment]
Är denna fortfarande relevant / möjligt i den senaste uppdaringen? @NEAC2004

**Comment by NEAC2004** [comment]
yup
@ThunbergOlle

**Comment by ThunbergOlle** [comment]
Hur mycket har detta använts? Krävs en full wipe?
